# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_X6S-NEG5BSXvbGzXHKigMhfiyU16An

CALCULAR MONTO FINAL
"""

# Leer la cantidad de productos
N = int(input("Ingrese el número de productos: "))
subtotal = 0

# Calcular el subtotal
for i in range(1, N + 1):
    precio = float(input(f"Ingrese el precio del producto {i}: "))
    subtotal += precio

# Calcular IGV y total
IGV = subtotal * 0.18
total = subtotal + IGV

# Mostrar resultados
print(f"Subtotal: {subtotal}")
print(f"IGV (18%): {IGV}")
print(f"Total a pagar: {total}")