# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTi2Pc2br4-M4CFoMtaQFbJ25WcXoh0Z

ESTADO ACADEMICO
"""

while True:
    # Leer el nombre del estudiante
    nombre = input("Ingrese el nombre del estudiante (o FIN para terminar): ")

    if nombre.upper() == "FIN":
        break

    # Leer las tres notas parciales
    nota1 = float(input("Ingrese la primera nota del estudiante: "))
    nota2 = float(input("Ingrese la segunda nota del estudiante: "))
    nota3 = float(input("Ingrese la tercera nota del estudiante: "))

    # Calcular el promedio
    promedio = (nota1 + nota2 + nota3) / 3

    # Determinar el estado académico
    if promedio >= 15:
        estado = "Aprobado"
    elif promedio >= 11:
        estado = "Recuperación"
    else:
        estado = "Desaprobado"

    # Mostrar mensaje personalizado
    print(f"Hola {nombre}, tu estado es: {estado}")